### ISSUE TITLE
Saving multiple?

### ISSUE THREAD

**Issue by coutofx** [bephp/activerecord#20]
## Congratulations on your project !

-----------------  **Question 1** -----------------

**Saving/ Update/ Delete multiple?**

> $user = new User();
> 
> $insert = [
>     [ 'username' => 'User 1' ],
>     ['username' => 'User 2'],
>     ['username' => User 3']
> ];
> $user->insert( $insert );

-----------------  **Question 2** -----------------

> JOIN, RIGHT JOIN and LEFT JOIN in BEPHP/activerecord ???

-----------------  **Question 3** -----------------

> Clear entry against SQL injection ???

----------------------------------------------------

**_Thank you!_**

**Comment by lloydzhou** [comment]
hi @coutofx,

1. do not support multiple insert / update.
2. do not support join, this library using "lazyload" to handle relations.
3. about SQL injection, this library using PDO, see php document and this issue on stackoverflow:
http://php.net/manual/en/pdo.prepared-statements.php
http://stackoverflow.com/questions/134099/are-pdo-prepared-statements-sufficient-to-prevent-sql-injection
