### ISSUE TITLE
how to show sql errors 

### ISSUE THREAD

**Issue by hobrt-programming** [bephp/activerecord#21]
hello pleas how i show sql errors if i use activerecord and thanks for this simple library .

**Comment by lloydzhou** [comment]
@hobrt-programming 

this library did not have logging, so you can just using this code for debug sql... :disappointed: 
 
https://github.com/bephp/activerecord/blob/master/ActiveRecord.php#L247

**Comment by lloydzhou** [comment]
@hobrt-programming 
if you have time, you can make pull request to this feature :smile:

**Comment by hobrt-programming** [comment]
ok thanks for your reply i add it on _query function 
187
`    public static function _query($sql, $param = array(), $obj = null, $single=false) {
        $sth = self::$db->prepare($sql);
        if ($sth) {
            $called_class = get_called_class();
	    $sth->setFetchMode( PDO::FETCH_INTO , ($obj ? $obj : new $called_class ));
            $e = $sth->execute($param);
            if(!$e)
                die($sth->errorInfo()[2]);
            if ($single) return $sth->fetch( PDO::FETCH_INTO ) ? $obj->dirty() : false;
            $result = array();
            while ($obj = $sth->fetch( PDO::FETCH_INTO )) $result[] = clone $obj->dirty();
            return $result;
        }
        print_r(self::$db->errorInfo());
        return false;
    }`
202
