### ISSUE TITLE
支持多个数据库实例

### ISSUE THREAD

**Issue by longhtml** [bephp/activerecord#6]
你好。 使用场景可以读取多个数据库，“主库、从库”不同配置。 

ActiveRecord::setDb(new PDO($dsn, $user, $password, array(PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION)));

ActiveRecord类   public static $db;

**Comment by lloydzhou** [comment]
你也看到了ActiveRecord类其实是使用static变量来保存PDO对象，所以其实并不支持主从数据库配置。

我个人觉得ActiveRecord只是提供了一种比较方便，简洁的方式访问数据库。在性能方面并没有经过严格测试。所以不建议在大型项目，特别是需要使用主从数据库的场景使用这个库。

当然，如果你喜欢这个库。
你也可以fork之后，更改代码提供你需要的特性。
也欢迎提交pull request

**Comment by lloydzhou** [comment]
@longhtml 
刚刚查了下官方文档 http://php.net/manual/zh/intro.mysqlnd-ms.php
有个mysqlnd-ms插件，可以在pdo那一层直接实现你需要的主从配置。

所以，如果你使用这个插件，就可以不用在代码层面管理你的mysql集群主从切换。

所以，这个插件可以和ActiveRecord配合访问mysql集群。

**Comment by longhtml** [comment]
php5.2环境，看来是够呛！！ 不过很喜欢activerecord，面向对象功底深！

**Comment by lloydzhou** [comment]
@longhtml 

http://php.net/manual/zh/mysqlnd-ms.requirements.php

要求PHP 5.3.6 或更高版本。php7都出来了，5.2也该升级了 :smiley:

**Comment by lloydzhou** [comment]
其实，说什么面向对象功底什么的，其实很一般。。。
只是个人喜欢小而美的东西。特别是小而美的代码 :smile:
