### ISSUE TITLE
find() 结果

### ISSUE THREAD

**Issue by Shangshj** [bephp/activerecord#8]
如何能方便判断一个查询结果是不是为空？比如：
`if(!$user->eq('email', $email)->find()){}`

**Comment by lloydzhou** [comment]
find始终返回的是一个Activerecord对象，所以如果你想要判断是不是真的查询到了数据，你可以试试下面的语句(使用其中的一个字段来判断，比如id :smile: )：

    if(!$user->eq('email', $email)->find()->id){
        //$user->...
    }

**Comment by Shangshj** [comment]
好的，谢谢！

**Comment by lloydzhou** [comment]
@Shangshj 
不用客气，有问题欢迎一起讨论
